services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    networks:
      - reverse-proxy
    volumes:
      - ./config:/app/config
      - /data/appdata/glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - path: /run/secrets/glance
        required: false
      - path: /home/joey/.local/glance/.env
        required: true
    labels:
      caddy: glance.localhost
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  reverse-proxy:
    external: true
