services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "4433:4433"
    networks:
      - caddy
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy.email: "joey@jafner.net"
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - caddy
    labels:
      caddy: test2.jafner.net:4433
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    name: caddy


