- name: Joey
  columns:
    - size: small
      widgets:
        - type: weather
          units: imperial
          hour-format: 12h
          location: Seattle, Washington, United States
        - type: calendar
          first-day-of-week: monday

    - size: full
      widgets:
        - type: group
          widgets:
            - type: docker-containers
              hide-by-default: false
    - size: small
      widgets:
        - type: group
          widgets:
            - type: releases
              show-source-icon: true
              repositories:
                - NixOS/nixpkgs
                - nix-community/home-manager
                - zed-industries/zed
                - zen-browser/desktop
                - obsproject/obs-studio
                - glanceapp/glance

            - type: repository
              repository: Jafner/Jafner.net
              pull-requests-limit: 5
              issues-limit: 5
              commits-limit: 5

            - type: repository
              repository: Jafner/5etools-docker
              pull-requests-limit: 5
              issues-limit: 5
              commits-limit: 5

            - type: repository
              repository: Jafner/dotfiles
              pull-requests-limit: 5
              issues-limit: 5
              commits-limit: 5
